Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

Load and Prepare the Data

In [3]:
# Load your dataset
data = pd.read_csv('C:/Sush/Mini Project/Mini-Project/Bengaluru2009-2019.csv')

In [4]:
# Check for missing values
print(data.isnull().sum())

date_time            0
maxtempC             0
mintempC             0
totalSnow_cm         0
sunHour              0
uvIndex              0
uvIndex.1            0
moon_illumination    0
moonrise             0
moonset              0
sunrise              0
sunset               0
DewPointC            0
FeelsLikeC           0
HeatIndexC           0
WindChillC           0
WindGustKmph         0
cloudcover           0
humidity             0
precipMM             0
pressure             0
tempC                0
visibility           0
winddirDegree        0
windspeedKmph        0
dtype: int64

In [5]:
data.head()

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,01-01-2009 00:00,27,12,0,11.6,5,1,31,9:58 AM,10:03 PM,...,18,11,2,91,0.0,1014,14,10,109,8
1,01-01-2009 01:00,27,12,0,11.6,5,1,31,9:58 AM,10:03 PM,...,17,9,2,93,0.0,1014,14,7,85,6
2,01-01-2009 02:00,27,12,0,11.6,5,1,31,9:58 AM,10:03 PM,...,16,7,2,94,0.0,1014,13,5,61,4
3,01-01-2009 03:00,27,12,0,11.6,5,1,31,9:58 AM,10:03 PM,...,15,5,2,96,0.0,1014,12,2,37,3
4,01-01-2009 04:00,27,12,0,11.6,5,1,31,9:58 AM,10:03 PM,...,18,5,1,88,0.0,1015,14,5,45,3

In [6]:
data.describe()

,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,DewPointC,FeelsLikeC,HeatIndexC,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
count,96432.000000,96432.000000,96432.0,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000,96432.000000
mean,29.646093,19.336735,0.0,10.653484,5.900448,4.013751,46.094077,16.085418,25.002261,25.269662,24.422152,17.370966,34.847488,64.895460,0.077719,1010.554225,23.979810,9.274162,176.182097,12.448938
std,3.446427,2.773771,0.0,1.986738,0.851346,2.869923,31.249725,4.161604,4.586926,4.430811,4.516766,7.426413,28.391021,21.856869,0.385865,3.187016,4.540028,2.184726,89.443207,5.716769
min,18.000000,11.000000,0.0,4.200000,4.000000,1.000000,0.000000,-9.000000,12.000000,13.000000,12.000000,0.000000,0.000000,6.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000
25%,27.000000,18.000000,0.0,8.800000,5.000000,1.000000,18.000000,14.000000,21.000000,22.000000,21.000000,12.000000,9.000000,49.000000,0.000000,1008.000000,21.000000,10.000000,94.000000,8.000000
50%,29.000000,20.000000,0.0,11.600000,6.000000,5.000000,46.000000,18.000000,25.000000,25.000000,24.000000,17.000000,29.000000,68.000000,0.000000,1010.000000,23.000000,10.000000,163.000000,12.000000
75%,32.000000,21.000000,0.0,11.600000,6.000000,7.000000,73.000000,19.000000,28.000000,28.000000,27.000000,22.000000,54.000000,83.000000,0.000000,1013.000000,27.000000,10.000000,262.000000,16.000000
max,40.000000,28.000000,0.0,12.900000,8.000000,10.000000,100.000000,25.000000,43.000000,43.000000,42.000000,53.000000,100.000000,100.000000,16.900000,1021.000000,40.000000,20.000000,360.000000,41.000000

In [7]:
data.shape

(96432, 25)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96432 entries, 0 to 96431
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date_time          96432 non-null  object
 1   maxtempC           96432 non-null  int64
 2   mintempC           96432 non-null  int64
 3   totalSnow_cm       96432 non-null  int64
 4   sunHour            96432 non-null  float64
 5   uvIndex            96432 non-null  int64
 6   uvIndex.1          96432 non-null  int64
 7   moon_illumination  96432 non-null  int64
 8   moonrise           96432 non-null  object
 9   moonset            96432 non-null  object
 10  sunrise            96432 non-null  object
 11  sunset             96432 non-null  object
 12  DewPointC          96432 non-null  int64
 13  FeelsLikeC         96432 non-null  int64
 14  HeatIndexC         96432 non-null  int64
 15  WindChillC         96432 non-null  int64
 16  WindGustKmph       96432 non-null  int64
 17  cloudcover         96432 non-null  int64
 18  humidity           96432 non-null  int64
 19  precipMM           96432 non-null  float64
 20  pressure           96432 non-null  int64
 21  tempC              96432 non-null  int64
 22  visibility         96432 non-null  int64
 23  winddirDegree      96432 non-null  int64
 24  windspeedKmph      96432 non-null  int64
dtypes: float64(2), int64(18), object(5)
memory usage: 18.4+ MB

In [9]:
data.columns

Index(['date_time', 'maxtempC', 'mintempC', 'totalSnow_cm', 'sunHour',
       'uvIndex', 'uvIndex.1', 'moon_illumination', 'moonrise', 'moonset',
       'sunrise', 'sunset', 'DewPointC', 'FeelsLikeC', 'HeatIndexC',
       'WindChillC', 'WindGustKmph', 'cloudcover', 'humidity', 'precipMM',
       'pressure', 'tempC', 'visibility', 'winddirDegree', 'windspeedKmph'],
      dtype='object')

In [11]:
data = data.dropna() # Dropping rows with missing values